# To learn about Buck see [Docs](https://buckbuild.com/).
# To run your application with Buck:
# - install Buck
# - `npm start` - to start the packager
# - `cd android`
# - `keytool -genkey -v -keystore keystores/debug.keystore -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"`
# keytool -genkey -v -keystore keystores/debug.keystore -keysize 1024 -alias b4a -validity 14000 -keypass 123456 -storepass 123456 -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"
# https://www.b4x.com/android/forum/threads/jarsigner-error-java-security-signatureexception-private-key-algorithm-is-not-compatible.87699/#content
# - `./gradlew :app:copyDownloadableDepsToLibs` - make all Gradle compile dependencies available to Buck
# - `buck install -r android/app` - compile, install and run application
#

lib_deps = []

for jarfile in glob(['libs/*.jar']):
  name = 'jars__' + jarfile[jarfile.rindex('/') + 1: jarfile.rindex('.jar')]
  lib_deps.append(':' + name)
  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

for aarfile in glob(['libs/*.aar']):
  name = 'aars__' + aarfile[aarfile.rindex('/') + 1: aarfile.rindex('.aar')]
  lib_deps.append(':' + name)
  android_prebuilt_aar(
    name = name,
    aar = aarfile,
  )

android_library(
    name = "all-libs",
    exported_deps = lib_deps,
)

android_library(
    name = "app-code",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    deps = [
        ":all-libs",
        ":build_config",
        ":res",
    ],
)

android_build_config(
    name = "build_config",
    package = "com.bucktest",
)

android_resource(
    name = "res",
    package = "com.bucktest",
    res = "src/main/res",
)

android_binary(
    name = "app",
    keystore = "//android/keystores:debug",
    manifest = "src/main/AndroidManifest.xml",
    manifest_entries = {
        'version_code': 12,
        'version_name': '2.0',
        'min_sdk_version': 16,
        'target_sdk_version': 25
    },
    package_type = "debug",
    deps = [
        ":app-code",
    ],
)
